# Generated by Django 4.2 on 2023-04-09 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='donor',
            name='wilaya',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='Daiira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('wilaya_n', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor.wilaya')),
            ],
        ),
    ]
