# Generated by Django 4.2 on 2023-04-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_wilaya_alter_donor_wilaya_daiira'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daiira',
            name='id',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='wilaya',
        ),
        migrations.AddField(
            model_name='donor',
            name='email',
            field=models.EmailField(default='gmail@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='donor',
            name='n_tel',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='donor',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='daiira',
            name='number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donor',
            name='blood',
            field=models.CharField(choices=[('chlef', 2)], max_length=40),
        ),
    ]
