# Generated by Django 4.2 on 2023-04-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_remove_daiira_id_remove_donor_wilaya_donor_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=3)),
                ('number_type', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='donor',
            name='blood',
        ),
        migrations.AddField(
            model_name='daiira',
            name='number_in_daiira',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='donor',
            name='daiira',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='wilaya',
            name='number_in_wilaya',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='donor',
            name='email',
            field=models.EmailField(max_length=120),
        ),
    ]
