# Generated by Django 4.2 on 2023-04-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0004_bloodtype_remove_donor_blood_daiira_number_in_daiira_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='blood',
            field=models.CharField(blank=True, choices=[], max_length=3),
        ),
    ]
