# Generated by Django 4.2 on 2023-04-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0006_donor_wilaya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='blood',
            field=models.CharField(choices=[('A-', 'A-'), ('A+', 'A+'), ('O-', 'O-'), ('O+', 'O+'), ('B-', 'B-'), ('B+', 'B+'), ('AB-', 'AB-'), ('AB+', 'AB+')], max_length=3),
        ),
        migrations.AlterField(
            model_name='donor',
            name='wilaya',
            field=models.CharField(choices=[(2, 'chlef')], max_length=30),
        ),
    ]
