# Generated by Django 4.2 on 2023-04-09 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0007_alter_donor_blood_alter_donor_wilaya'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='wilaya',
        ),
    ]
