# Generated by Django 4.2 on 2023-04-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0009_donor_wilaya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daiira',
            name='wilaya_n',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='donor',
            name='n_tel',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='donor',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='donor',
            name='wilaya',
            field=models.CharField(choices=[(1, ' أدرار'), (2, ' الشلف'), (3, ' الأغواط'), (4, ' أم البواقي'), (5, ' باتنة'), (6, ' بجاية'), (7, ' بسكرة'), (8, ' بشار'), (9, ' البليدة'), (10, ' البويرة'), (11, ' تمنراست'), (12, ' تبسة'), (13, ' تلمسان'), (14, ' تيارت'), (15, ' تيزي وزو'), (16, ' الجزائر'), (17, ' الجلفة'), (18, ' جيجل'), (19, ' سطيف'), (20, ' السعيدة'), (21, ' سكيكدة'), (22, ' سيدي بلعباس'), (23, ' عنابة'), (24, ' قالمة'), (25, ' قسنطينة'), (26, ' المدية'), (27, ' مستغانم'), (28, ' المسيلة'), (29, ' معسكر'), (30, ' ورقلة'), (31, ' وهران'), (32, ' البيض'), (33, ' إليزي'), (34, ' برج بوعريريج'), (35, ' بومرداس'), (36, ' الطارف'), (37, ' تندوف'), (38, ' تسيمسيلت'), (39, ' الوادي(واد سوف)'), (40, ' خنشلة'), (41, ' سوق اهراس'), (42, ' تيبازة'), (43, ' ميلة'), (44, ' عين الدفلى'), (45, ' النعامة'), (46, ' عين تموشنت'), (47, ' غرادية'), (48, ' غليزان'), (49, ' تيميمون'), (50, ' برج باجي مختار'), (51, ' أولاد جلال'), (52, ' بني عباس'), (53, ' عين صالح'), (54, ' عين قزام'), (55, ' توقرت'), (56, ' جانت'), (57, ' المغير'), (58, ' المنيعة')], max_length=30),
        ),
    ]
