# Generated by Django 4.2 on 2023-04-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0011_delete_daiira'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daiira',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('wilaya_n', models.CharField(max_length=50)),
                ('number_in_daiira', models.IntegerField(default=0)),
            ],
        ),
    ]
