# Generated by Django 4.2 on 2023-04-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0012_daiira'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daiira',
            name='wilaya_n',
            field=models.IntegerField(),
        ),
    ]
