# Generated by Django 4.2 on 2023-04-13 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0014_alter_donor_daiira_alter_donor_wilaya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='blood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor.bloodtype'),
        ),
    ]
