# Generated by Django 4.2 on 2023-04-13 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0015_alter_donor_blood'),
    ]

    operations = [
        migrations.AddField(
            model_name='daiira',
            name='wilaya',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='donor.wilaya'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='blood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donor.bloodtype'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='daiira',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donor.daiira'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='wilaya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donor.wilaya'),
        ),
    ]
