# Generated by Django 4.2 on 2023-04-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0018_remove_daiira_wilaya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodtype',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
