# Generated by Django 4.2 on 2023-04-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0020_alter_bloodtype_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='email',
            field=models.EmailField(max_length=120),
        ),
    ]
