# Generated by Django 4.2 on 2023-04-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0022_alter_donor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='email',
            field=models.EmailField(max_length=120, unique=True),
        ),
    ]
