# Generated by Django 4.2 on 2023-05-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0023_alter_donor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='n_tel',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
