# Generated by Django 4.2 on 2023-05-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0025_donor_age_donor_date_signup_donor_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='age',
            field=models.IntegerField(default=18),
        ),
    ]
