# Generated by Django 4.2 on 2023-05-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0026_alter_donor_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='status',
            field=models.CharField(choices=[('enable', 'Enable'), ('disable', 'Disable')], default='enable', max_length=7),
        ),
    ]
