# Generated by Django 4.2 on 2023-05-07 18:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0027_donor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='birthdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='donor',
            name='call_time',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
